spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:qaisar}
    password: ${DB_PASSWORD:qwerty}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:savvy_database}
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: qaisar
#    password: qwerty
  main:
    allow-circular-references: true
  liquibase:
    change-log: db.changelog/changelog.xml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bot:
  name: SavvyBot
  token: ${BOT_API_TOKEN}
  weather_token: ${WEATHER_API_TOKEN}

server:
  port: 0
