spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  rabbitmq:
    host: localhost
    port: 5672
    username: qaisar
    password: p@ssw0rd
  liquibase:
    change-log: db.changelog/changelog.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
bot:
  name: SavvyBot
  token: ${BOT_API_TOKEN}
  weather_token: ${WEATHER_API_TOKEN}
